# Generated by Django 4.2.6 on 2023-10-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_commentary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
